service: products-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:GetItem'
            - 'dynamodb:DeleteItem'
            - 'dynamodb:Scan'
          Resource:
            - { 'Fn::GetAtt': ['Products', 'Arn'] }

functions:
  createProduct:
    handler: src/handlers.createProduct
    events:
      - httpApi:
          path: /api/v1/product
          method: post

  getProduct:
    handler: src/handlers.getProduct
    events:
      - httpApi:
          path: /api/v1/product
          method: get

  getProductByID:
    handler: src/handlers.getProductByID
    events:
      - httpApi:
          path: /api/v1/product/{id}
          method: get

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

resources:
  Resources:
    Products:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: productID
            AttributeType: S
        KeySchema:
          - AttributeName: productID
            KeyType: HASH
